# Generated by Django 4.0.5 on 2022-06-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Album',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Artist',
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Genre',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255)),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.album')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.genre')),
            ],
            options={
                'verbose_name_plural': 'Song',
                'db_table': 'song',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.artist'),
        ),
    ]
