# Generated by Django 4.0.5 on 2022-06-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(db_column='album_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_id',
            field=models.ForeignKey(db_column='genre_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.genre'),
        ),
    ]
