# Generated by Django 4.0.5 on 2022-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_artist_artist_name_alter_genre_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
