# Generated by Django 4.0.5 on 2022-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_song_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
