# Generated by Django 4.0.5 on 2022-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_song_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(check=models.Q(('song_name__length__gt', 0)), name='song_check_constraint'),
        ),
    ]
