# Generated by Django 4.0.5 on 2022-07-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_song_song_name_song_song_check_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
